USE [master]
GO
/****** Object:  Database [UserLogin]   ******/
DROP DATABASE [UserLogin]
GO
/****** Object:  Database [UserLogin]   ******/
CREATE DATABASE [UserLogin]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UserLogin', FILENAME = N'D:\SQL2019\MSSQL15.MSSQLSERVER\MSSQL\DATA\UserLogin.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'UserLogin_log', FILENAME = N'D:\SQL2019\MSSQL15.MSSQLSERVER\MSSQL\DATA\UserLogin_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UserLogin].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UserLogin] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UserLogin] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UserLogin] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UserLogin] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UserLogin] SET ARITHABORT OFF 
GO

ALTER DATABASE [UserLogin] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [UserLogin] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UserLogin] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UserLogin] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UserLogin] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UserLogin] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UserLogin] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UserLogin] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UserLogin] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UserLogin] SET  ENABLE_BROKER 
GO

ALTER DATABASE [UserLogin] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UserLogin] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UserLogin] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UserLogin] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UserLogin] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UserLogin] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UserLogin] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UserLogin] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [UserLogin] SET  MULTI_USER 
GO

ALTER DATABASE [UserLogin] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UserLogin] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UserLogin] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [UserLogin] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [UserLogin] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [UserLogin] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [UserLogin] SET QUERY_STORE = OFF
GO

ALTER DATABASE [UserLogin] SET  READ_WRITE 
GO

/****** Object:  Table [dbo].[Login]    Script Date: 7/8/2022 6:52:12 PM ******/
SET ANSI_NULLS ON
GO
USE [UserLogin]
Go
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Login](
	[LoginId] [bigint] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](50) NULL,
	[Password] [nvarchar](100) NULL,
	[Email] [nvarchar](50) NULL,
	[Attempt] [int] NULL,
	[DateCreated] [datetime] NULL,
	[DateUpdated] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[LoginId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


